# This is a basic workflow to help you get started with Actions

name: Deploy to Aliyun

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
         
      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
      - name: Install dependecies
        run: |
          # 安装Node.js
          sudo apt-get update
          sudo apt-get install -y nodejs
          # 安装yarn
          npm install -g yarn
          yarn
          yarn run docs:build 
      #- name: Build and Deploy
       # env:
        #  MY_SECRET: ${{ secrets.MYSITE }}
       # run: |
        #  yarn run deploy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # publish_dir: ./docs/.vitepress/dist
          destination_dir: .
          external_repository: https://github.com/zhangqf/mysite
          force_orphan: true
          ssh_private_key: ${{ secrets.MYSITE }}
          




          
